name: Publish Email-sender-dto
on:
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: publish
        uses: anton-nagornyi/anyit-messenger/.github/composite-actions/publish@main
        with:
          working-directory: packages/email-sender-dto
          npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
